import type { RuleTemplate } from '@uni-conf/types'

export const BUILTIN_TEMPLATES: RuleTemplate[] = [
  {
    id: 'tpl-ai',
    name: 'AI 服务',
    nameEn: 'AI Services',
    description: 'OpenAI, Claude, Gemini, Copilot 等 AI 服务',
    descriptionEn: 'OpenAI, Claude, Gemini, Copilot and other AI services',
    category: 'ai',
    isBuiltin: true,
    createdAt: '2025-01-01T00:00:00Z',
    suggestedGroupName: 'AI',
    rules: [
      { type: 'DOMAIN-SUFFIX', payload: 'openai.com', enabled: true, order: 0, compatibility: [], notes: 'OpenAI' },
      { type: 'DOMAIN-SUFFIX', payload: 'oaistatic.com', enabled: true, order: 1, compatibility: [], notes: 'OpenAI static' },
      { type: 'DOMAIN-SUFFIX', payload: 'chatgpt.com', enabled: true, order: 2, compatibility: [], notes: 'ChatGPT' },
      { type: 'DOMAIN-SUFFIX', payload: 'anthropic.com', enabled: true, order: 3, compatibility: [], notes: 'Claude' },
      { type: 'DOMAIN-SUFFIX', payload: 'claude.ai', enabled: true, order: 4, compatibility: [], notes: 'Claude' },
      { type: 'DOMAIN-SUFFIX', payload: 'gemini.google.com', enabled: true, order: 5, compatibility: [], notes: 'Gemini' },
      { type: 'DOMAIN-KEYWORD', payload: 'openai', enabled: true, order: 6, compatibility: [], notes: 'OpenAI keyword' },
      { type: 'DOMAIN-SUFFIX', payload: 'copilot.microsoft.com', enabled: true, order: 7, compatibility: [], notes: 'Copilot' },
      { type: 'DOMAIN-SUFFIX', payload: 'perplexity.ai', enabled: true, order: 8, compatibility: [], notes: 'Perplexity' },
      { type: 'DOMAIN-SUFFIX', payload: 'cursor.sh', enabled: true, order: 9, compatibility: [], notes: 'Cursor' },
      { type: 'DOMAIN-SUFFIX', payload: 'groq.com', enabled: true, order: 10, compatibility: [], notes: 'Groq' },
      { type: 'DOMAIN-SUFFIX', payload: 'cohere.com', enabled: true, order: 11, compatibility: [], notes: 'Cohere' },
      { type: 'DOMAIN-SUFFIX', payload: 'mistral.ai', enabled: true, order: 12, compatibility: [], notes: 'Mistral' },
    ],
  },
  {
    id: 'tpl-streaming',
    name: '流媒体',
    nameEn: 'Streaming',
    description: 'Netflix, YouTube, Disney+, Spotify 等流媒体服务',
    descriptionEn: 'Netflix, YouTube, Disney+, Spotify and other streaming services',
    category: 'streaming',
    isBuiltin: true,
    createdAt: '2025-01-01T00:00:00Z',
    suggestedGroupName: 'Streaming',
    rules: [
      { type: 'DOMAIN-SUFFIX', payload: 'netflix.com', enabled: true, order: 0, compatibility: [], notes: 'Netflix' },
      { type: 'DOMAIN-SUFFIX', payload: 'nflxso.net', enabled: true, order: 1, compatibility: [], notes: 'Netflix CDN' },
      { type: 'DOMAIN-SUFFIX', payload: 'nflximg.net', enabled: true, order: 2, compatibility: [], notes: 'Netflix images' },
      { type: 'DOMAIN-SUFFIX', payload: 'youtube.com', enabled: true, order: 3, compatibility: [], notes: 'YouTube' },
      { type: 'DOMAIN-SUFFIX', payload: 'youtu.be', enabled: true, order: 4, compatibility: [], notes: 'YouTube short' },
      { type: 'DOMAIN-SUFFIX', payload: 'googlevideo.com', enabled: true, order: 5, compatibility: [], notes: 'YouTube CDN' },
      { type: 'DOMAIN-SUFFIX', payload: 'disneyplus.com', enabled: true, order: 6, compatibility: [], notes: 'Disney+' },
      { type: 'DOMAIN-SUFFIX', payload: 'disney-plus.net', enabled: true, order: 7, compatibility: [], notes: 'Disney+ CDN' },
      { type: 'DOMAIN-SUFFIX', payload: 'hulu.com', enabled: true, order: 8, compatibility: [], notes: 'Hulu' },
      { type: 'DOMAIN-SUFFIX', payload: 'spotify.com', enabled: true, order: 9, compatibility: [], notes: 'Spotify' },
      { type: 'DOMAIN-SUFFIX', payload: 'scdn.co', enabled: true, order: 10, compatibility: [], notes: 'Spotify CDN' },
      { type: 'DOMAIN-SUFFIX', payload: 'primevideo.com', enabled: true, order: 11, compatibility: [], notes: 'Prime Video' },
      { type: 'DOMAIN-SUFFIX', payload: 'hbomax.com', enabled: true, order: 12, compatibility: [], notes: 'HBO Max' },
      { type: 'DOMAIN-SUFFIX', payload: 'max.com', enabled: true, order: 13, compatibility: [], notes: 'Max' },
      { type: 'DOMAIN-SUFFIX', payload: 'twitch.tv', enabled: true, order: 14, compatibility: [], notes: 'Twitch' },
    ],
  },
  {
    id: 'tpl-social',
    name: '社交媒体',
    nameEn: 'Social Media',
    description: 'Twitter/X, Instagram, Facebook, TikTok, Reddit、Discord 等社交平台',
    descriptionEn: 'Twitter/X, Instagram, Facebook, TikTok, Reddit, Discord and other social platforms',
    category: 'social',
    isBuiltin: true,
    createdAt: '2025-01-01T00:00:00Z',
    suggestedGroupName: 'Social',
    rules: [
      { type: 'DOMAIN-SUFFIX', payload: 'twitter.com', enabled: true, order: 0, compatibility: [], notes: 'Twitter/X' },
      { type: 'DOMAIN-SUFFIX', payload: 'x.com', enabled: true, order: 1, compatibility: [], notes: 'X' },
      { type: 'DOMAIN-SUFFIX', payload: 't.co', enabled: true, order: 2, compatibility: [], notes: 'Twitter short URL' },
      { type: 'DOMAIN-SUFFIX', payload: 'twimg.com', enabled: true, order: 3, compatibility: [], notes: 'Twitter images' },
      { type: 'DOMAIN-SUFFIX', payload: 'instagram.com', enabled: true, order: 4, compatibility: [], notes: 'Instagram' },
      { type: 'DOMAIN-SUFFIX', payload: 'cdninstagram.com', enabled: true, order: 5, compatibility: [], notes: 'Instagram CDN' },
      { type: 'DOMAIN-SUFFIX', payload: 'facebook.com', enabled: true, order: 6, compatibility: [], notes: 'Facebook' },
      { type: 'DOMAIN-SUFFIX', payload: 'fbcdn.net', enabled: true, order: 7, compatibility: [], notes: 'Facebook CDN' },
      { type: 'DOMAIN-SUFFIX', payload: 'tiktok.com', enabled: true, order: 8, compatibility: [], notes: 'TikTok' },
      { type: 'DOMAIN-SUFFIX', payload: 'tiktokcdn.com', enabled: true, order: 9, compatibility: [], notes: 'TikTok CDN' },
      { type: 'DOMAIN-SUFFIX', payload: 'reddit.com', enabled: true, order: 10, compatibility: [], notes: 'Reddit' },
      { type: 'DOMAIN-SUFFIX', payload: 'redd.it', enabled: true, order: 11, compatibility: [], notes: 'Reddit short' },
      { type: 'DOMAIN-SUFFIX', payload: 'discord.com', enabled: true, order: 12, compatibility: [], notes: 'Discord' },
      { type: 'DOMAIN-SUFFIX', payload: 'discordapp.com', enabled: true, order: 13, compatibility: [], notes: 'Discord CDN' },
    ],
  },
  {
    id: 'tpl-telegram',
    name: 'Telegram',
    nameEn: 'Telegram',
    description: 'Telegram 域名和常用 IP 段',
    descriptionEn: 'Telegram domains and common IP ranges',
    category: 'social',
    isBuiltin: true,
    createdAt: '2025-01-01T00:00:00Z',
    suggestedGroupName: 'Telegram',
    rules: [
      { type: 'DOMAIN-SUFFIX', payload: 'telegram.org', enabled: true, order: 0, compatibility: [], notes: 'Telegram' },
      { type: 'DOMAIN-SUFFIX', payload: 't.me', enabled: true, order: 1, compatibility: [], notes: 'Telegram links' },
      { type: 'IP-CIDR', payload: '149.154.160.0/20', enabled: true, order: 2, compatibility: [], notes: 'Telegram IP' },
      { type: 'IP-CIDR', payload: '91.108.4.0/22', enabled: true, order: 3, compatibility: [], notes: 'Telegram IP EU' },
    ],
  },
  {
    id: 'tpl-china-direct',
    name: '国内直连',
    nameEn: 'China Direct',
    description: '中国大陆域名和 IP 直连，无需代理',
    descriptionEn: 'China mainland domains and IPs connect directly without proxy',
    category: 'china',
    isBuiltin: true,
    createdAt: '2025-01-01T00:00:00Z',
    suggestedGroupName: 'DIRECT',
    rules: [
      { type: 'GEOSITE', payload: 'cn', enabled: true, order: 0, compatibility: [], notes: 'China domains via GeoSite' },
      { type: 'GEOIP', payload: 'CN', enabled: true, order: 1, noResolve: true, compatibility: [], notes: 'China IPs via GeoIP' },
    ],
  },
  {
    id: 'tpl-reject',
    name: '广告拦截',
    nameEn: 'Ad Block',
    description: '拦截常见广告、追踪和恶意域名',
    descriptionEn: 'Block common ads, tracking, and malicious domains',
    category: 'security',
    isBuiltin: true,
    createdAt: '2025-01-01T00:00:00Z',
    suggestedGroupName: 'REJECT',
    rules: [],
    remoteSets: [
      {
        name: 'AdGuard DNS Filter',
        url: 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt',
        format: 'text',
        updateInterval: 24,
        enabled: true,
        sortOrder: 20,
      },
    ],
  },
]

export function getTemplate(id: string): RuleTemplate | undefined {
  return BUILTIN_TEMPLATES.find((t) => t.id === id)
}

export function getTemplatesByCategory(category: string): RuleTemplate[] {
  return BUILTIN_TEMPLATES.filter((t) => t.category === category)
}
