import { DEFAULT_HEALTH_CHECK, isRuleSetFormatCompatible } from '@uni-conf/shared';
import type { DnsMode, ProxyNode, ProxyGroup, ProxyRule, RemoteRuleSet } from '@uni-conf/types';
import { resolveRemoteRuleSetForExport } from './remote-rule-set-resolver';

// ─── Mihomo YAML generator ────────────────────────────────────────────────────

interface MihomoGeneratorOptions {
  dnsMode?: DnsMode;
}

export function generateMihomoYaml(
  nodes: ProxyNode[],
  groups: ProxyGroup[],
  rules: ProxyRule[],
  remoteSets: RemoteRuleSet[],
  collectionNodeNames: Record<string, string[]> = {},
  options: MihomoGeneratorOptions = {}
): string {
  const lines: string[] = [];
  const serializedNodes = nodes
    .map((node) => ({ node, proxy: nodeToMihomo(node) }))
    .filter((item): item is { node: ProxyNode; proxy: string } => item.proxy !== null);
  const serializableNodes = serializedNodes.map((item) => item.node);
  const serializableNodeNames = new Set(serializableNodes.map((node) => node.name));
  const serializableCollectionNodeNames = filterCollectionNodeNames(
    collectionNodeNames,
    serializableNodeNames
  );

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push('# Generated by UniConf');
  lines.push(`# Generated at: ${new Date().toISOString()}`);
  lines.push('');

  // ── Basic settings ──────────────────────────────────────────────────────────
  lines.push('mixed-port: 7890');
  lines.push('allow-lan: false');
  lines.push('bind-address: "*"');
  lines.push('mode: rule');
  lines.push('log-level: warning');
  lines.push('ipv6: false');
  lines.push('external-controller: 127.0.0.1:9090');
  lines.push('');

  lines.push(...buildDnsLines(options.dnsMode ?? 'smart'));
  lines.push('');

  // ── Proxies ─────────────────────────────────────────────────────────────────
  if (serializedNodes.length === 0) {
    lines.push('proxies: []');
  } else {
    lines.push('proxies:');
    for (const { proxy } of serializedNodes) {
      lines.push(`  - ${proxy}`);
    }
  }
  lines.push('');

  // ── Proxy groups ─────────────────────────────────────────────────────────────
  const mihomoProxyGroups = groups.filter(isMihomoProxyGroup);
  if (mihomoProxyGroups.length === 0) {
    lines.push('proxy-groups: []');
  } else {
    lines.push('proxy-groups:');
    for (const group of mihomoProxyGroups) {
      lines.push(...groupToMihomo(group, serializableNodes, groups, serializableCollectionNodeNames));
    }
  }
  lines.push('');

  // ── Rule providers ────────────────────────────────────────────────────────────
  const enabledRemoteSets = sortRemoteRuleSets(remoteSets)
    .filter((rs) => rs.enabled)
    .map((rs) => ({ source: rs, resolved: resolveRemoteRuleSetForExport(rs, 'mihomo') }))
    .filter((item): item is { source: RemoteRuleSet; resolved: { url: string; format: RemoteRuleSet['format'] } } =>
      Boolean(item.resolved) && isRuleSetFormatCompatible('mihomo', item.resolved!.format)
    );
  if (enabledRemoteSets.length === 0) {
    lines.push('rule-providers: {}');
  } else {
    lines.push('rule-providers:');
    for (const { source: rs, resolved } of enabledRemoteSets) {
      const safeName = rs.name.replace(/[^a-zA-Z0-9_-]/g, '_');
      lines.push(`  ${safeName}:`);
      lines.push(`    type: http`);
      lines.push(`    behavior: ${rs.behavior}`);
      lines.push(`    url: "${resolved.url}"`);
      lines.push(`    path: ./ruleset/${safeName}.yaml`);
      lines.push(`    interval: ${rs.updateInterval * 3600}`);
    }
  }
  lines.push('');

  // ── Rules ────────────────────────────────────────────────────────────────────
  const enabledRules = rules
    .filter((r) => r.enabled)
    .sort((a, b) => a.order - b.order);
  const matchRule = enabledRules.find((r) => r.type === 'MATCH');

  lines.push('rules:');
  for (const rule of enabledRules) {
    if (rule.type === 'MATCH') continue;
    lines.push(`  - ${ruleToMihomo(rule, groups)}`);
  }

  for (const { source: rs } of enabledRemoteSets) {
    const safeName = rs.name.replace(/[^a-zA-Z0-9_-]/g, '_');
    const group = groups.find((g) => g.id === rs.targetGroupId);
    const targetGroup = group ? resolveMihomoPolicyName(group) : rs.targetGroupId;
    lines.push(`  - RULE-SET,${safeName},${targetGroup}`);
  }

  if (matchRule) {
    lines.push(`  - ${ruleToMihomo(matchRule, groups)}`);
  } else {
    const defaultTarget = defaultPolicyName(groups);
    if (defaultTarget) {
      lines.push(`  - MATCH,${defaultTarget}`);
    } else {
      lines.push('  - MATCH,DIRECT');
    }
  }

  return lines.join('\n');
}

function buildDnsLines(mode: DnsMode): string[] {
  const lines = [
    'dns:',
    '  enable: true',
    `  enhanced-mode: ${mode === 'fake-ip' ? 'fake-ip' : 'redir-host'}`,
  ];

  if (mode === 'fake-ip') {
    lines.push('  fake-ip-range: 198.18.0.1/16');
    lines.push('  fake-ip-filter:');
    lines.push('    - "*.lan"');
    lines.push('    - "*.local"');
    lines.push('    - "localhost.ptlogin2.qq.com"');
    lines.push('    - "localhost.sec.qq.com"');
    lines.push('    - "+.msftconnecttest.com"');
    lines.push('    - "+.msftncsi.com"');
  }

  lines.push('  default-nameserver:');
  lines.push('    - 223.5.5.5');
  lines.push('    - 119.29.29.29');
  lines.push('  nameserver:');
  lines.push('    - https://223.5.5.5/dns-query');
  lines.push('    - https://120.53.53.53/dns-query');

  if (mode === 'compatible') {
    return lines;
  }

  lines.push('  fallback:');
  lines.push('    - tls://8.8.8.8');
  lines.push('    - tls://1.1.1.1');
  lines.push('  fallback-filter:');
  lines.push('    geoip: true');
  lines.push('    geoip-code: CN');
  lines.push('    ipcidr:');
  lines.push('      - 240.0.0.0/4');
  lines.push('  nameserver-policy:');
  lines.push('    "geosite:cn":');
  lines.push('      - https://223.5.5.5/dns-query');
  lines.push('      - https://120.53.53.53/dns-query');
  return lines;
}

function sortRemoteRuleSets(remoteSets: RemoteRuleSet[]): RemoteRuleSet[] {
  return [...remoteSets].sort((a, b) => a.sortOrder - b.sortOrder || a.createdAt.localeCompare(b.createdAt));
}

// ─── Node serialization ───────────────────────────────────────────────────────

function nodeToMihomo(node: ProxyNode): string | null {
  const nativeProxy = nativeMihomoProxy(node);
  if (nativeProxy) return JSON.stringify(nativeProxy);

  const cfg = node.parsedConfig;
  const name = escapeName(node.name);

  switch (node.protocol) {
    case 'ss': {
      const method = (cfg.extra?.cipher as string) ?? (cfg.extra?.method as string) ?? 'aes-256-gcm';
      const pass = cfg.password ?? '';
      return `{name: "${name}", type: ss, server: ${node.server}, port: ${node.port}, cipher: "${method}", password: "${pass}"}`;
    }
    case 'ssr': {
      const method = (cfg.extra?.cipher as string) ?? (cfg.extra?.method as string) ?? 'aes-256-cfb';
      const pass = cfg.password ?? '';
      const protocol = (cfg.extra?.protocol as string) ?? 'origin';
      const obfs = (cfg.extra?.obfs as string) ?? 'plain';
      let obj = `{name: "${name}", type: ssr, server: ${node.server}, port: ${node.port}, cipher: "${method}", password: "${pass}", protocol: "${protocol}", obfs: "${obfs}"`;
      if (cfg.extra?.protocolParam) obj += `, protocol-param: "${String(cfg.extra.protocolParam)}"`;
      if (cfg.extra?.obfsParam) obj += `, obfs-param: "${String(cfg.extra.obfsParam)}"`;
      obj += '}';
      return obj;
    }
    case 'vmess': {
      const uuid = cfg.uuid ?? '';
      const alterId = (cfg.extra?.alterId as number) ?? 0;
      const network = cfg.network ?? 'tcp';
      let obj = `{name: "${name}", type: vmess, server: ${node.server}, port: ${node.port}, uuid: "${uuid}", alterId: ${alterId}, cipher: auto, tls: ${cfg.tls ?? false}, network: "${network}"`;
      if (network === 'ws') {
        const wsPath = cfg.wsPath ?? '/';
        obj += `, ws-opts: {path: "${wsPath}"`;
        if (cfg.wsHeaders && Object.keys(cfg.wsHeaders).length > 0) {
          const host = cfg.wsHeaders['Host'] ?? cfg.wsHeaders['host'] ?? node.server;
          obj += `, headers: {Host: "${host}"}`;
        }
        obj += '}';
      }
      if (cfg.sni) obj += `, servername: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'vless': {
      const uuid = cfg.uuid ?? '';
      const network = cfg.network ?? 'tcp';
      const flow = (cfg.extra?.flow as string) ?? '';
      let obj = `{name: "${name}", type: vless, server: ${node.server}, port: ${node.port}, uuid: "${uuid}", tls: ${cfg.tls ?? false}, network: "${network}"`;
      if (flow) obj += `, flow: "${flow}"`;
      if (cfg.sni) obj += `, servername: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      const reality = vlessRealityOptions(cfg.extra);
      if (reality) {
        obj += `, reality-opts: {public-key: "${reality.publicKey}", short-id: "${reality.shortId}"}`;
      }
      obj += '}';
      return obj;
    }
    case 'trojan': {
      const pass = cfg.password ?? '';
      let obj = `{name: "${name}", type: trojan, server: ${node.server}, port: ${node.port}, password: "${pass}"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'hysteria2': {
      const pass = cfg.password ?? (cfg.extra?.auth as string) ?? '';
      const obfs = cfg.extra?.obfs as string | undefined;
      const obfsPassword = cfg.extra?.obfsPassword as string | undefined;
      let obj = `{name: "${name}", type: hysteria2, server: ${node.server}, port: ${node.port}, password: "${pass}"`;
      if (obfs) obj += `, obfs: "${obfs}"`;
      if (obfsPassword) obj += `, obfs-password: "${obfsPassword}"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'hysteria': {
      const authStr = cfg.password ?? (cfg.extra?.authStr as string) ?? (cfg.extra?.auth as string) ?? '';
      const protocol = (cfg.extra?.protocol as string) ?? 'udp';
      const upMbps = (cfg.extra?.upMbps as number) ?? 100;
      const downMbps = (cfg.extra?.downMbps as number) ?? 100;
      let obj = `{name: "${name}", type: hysteria, server: ${node.server}, port: ${node.port}, auth-str: "${authStr}", protocol: "${protocol}", up: "${upMbps} Mbps", down: "${downMbps} Mbps"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'tuic': {
      const uuid = cfg.uuid ?? '';
      const pass = cfg.password ?? '';
      let obj = `{name: "${name}", type: tuic, server: ${node.server}, port: ${node.port}, uuid: "${uuid}", password: "${pass}"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'anytls': {
      const pass = cfg.password ?? '';
      const fingerprint = (cfg.extra?.['client-fingerprint'] as string | undefined)
        ?? (cfg.extra?.clientFingerprint as string | undefined);
      const alpn = cfg.extra?.alpn;
      let obj = `{name: "${name}", type: anytls, server: ${node.server}, port: ${node.port}, password: "${pass}"`;
      if (fingerprint) obj += `, client-fingerprint: "${fingerprint}"`;
      if (cfg.extra?.udp !== undefined) obj += `, udp: ${Boolean(cfg.extra.udp)}`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (Array.isArray(alpn) && alpn.length > 0) {
        obj += `, alpn: [${alpn.map((item) => `"${String(item)}"`).join(', ')}]`;
      }
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'socks5': {
      let obj = `{name: "${name}", type: socks5, server: ${node.server}, port: ${node.port}`;
      if (cfg.extra?.username) obj += `, username: "${cfg.extra.username}"`;
      if (cfg.password) obj += `, password: "${cfg.password}"`;
      if (cfg.tls) obj += `, tls: true`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'http':
    case 'https': {
      let obj = `{name: "${name}", type: http, server: ${node.server}, port: ${node.port}`;
      if (cfg.extra?.username) obj += `, username: "${cfg.extra.username}"`;
      if (cfg.password) obj += `, password: "${cfg.password}"`;
      if (node.protocol === 'https' || cfg.tls) obj += `, tls: true`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    default:
      return null;
  }
}

function nativeMihomoProxy(node: ProxyNode): Record<string, unknown> | null {
  const raw = nativeObject(node.rawConfig, 'mihomo');
  if (!isMihomoProxyShape(raw)) return null;
  return {
    ...raw,
    name: node.name,
    server: node.server,
    port: node.port,
  };
}

function vlessRealityOptions(extra: Record<string, unknown> | undefined): { publicKey: string; shortId: string } | null {
  if (!extra) return null;
  const nested = extra.reality && typeof extra.reality === 'object' && !Array.isArray(extra.reality)
    ? extra.reality as Record<string, unknown>
    : {};
  const publicKey = configString(extra.publicKey) ?? configString(nested.publicKey);
  const shortId = configString(extra.shortId) ?? configString(nested.shortId) ?? '';
  return publicKey ? { publicKey, shortId } : null;
}

function configString(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function nativeObject(rawConfig: unknown, key: string): Record<string, unknown> | null {
  if (!rawConfig || typeof rawConfig !== 'object' || Array.isArray(rawConfig)) return null;
  const raw = rawConfig as Record<string, unknown>;
  const nested = raw[key];
  if (nested && typeof nested === 'object' && !Array.isArray(nested)) return nested as Record<string, unknown>;
  return raw;
}

function isMihomoProxyShape(value: Record<string, unknown> | null): value is Record<string, unknown> {
  return Boolean(value && typeof value.type === 'string' && value.port !== undefined && value.server !== undefined);
}

// ─── Group serialization ──────────────────────────────────────────────────────

function groupToMihomo(
  group: ProxyGroup,
  allNodes: ProxyNode[],
  allGroups: ProxyGroup[],
  collectionNodeNames: Record<string, string[]>
): string[] {
  const lines: string[] = [];
  const name = escapeName(group.name);

  lines.push(`  - name: "${name}"`);
  lines.push(`    type: ${group.type}`);

  const proxies: string[] = [];

  for (const b of group.builtins) {
    proxies.push(b);
  }

  for (const gid of group.groupIds) {
    const nestedGroup = allGroups.find((item) => item.id === gid);
    if (nestedGroup) proxies.push(resolveMihomoPolicyName(nestedGroup));
  }

  const collectionNames = group.collectionIds.flatMap((id) => collectionNodeNames[id] ?? []);
  if (collectionNames.length > 0) {
    for (const nodeName of collectionNames) proxies.push(escapeName(nodeName));
  } else if (group.collectionIds.length === 0 && group.groupIds.length === 0 && group.builtins.length === 0) {
    for (const node of allNodes) proxies.push(escapeName(node.name));
  }

  const dedupedProxies = [...new Set(proxies)];
  if (dedupedProxies.length === 0) dedupedProxies.push('DIRECT');

  lines.push(`    proxies:`);
  for (const p of dedupedProxies) {
    lines.push(`      - "${p}"`);
  }

  if (['url-test', 'fallback', 'load-balance'].includes(group.type)) {
    lines.push(`    url: "${group.testUrl ?? DEFAULT_HEALTH_CHECK.testUrl}"`);
    lines.push(`    interval: ${group.interval ?? DEFAULT_HEALTH_CHECK.interval}`);
    if (group.tolerance !== undefined) {
      lines.push(`    tolerance: ${group.tolerance}`);
    }
    if (group.lazy !== undefined) {
      lines.push(`    lazy: ${group.lazy}`);
    }
  }

  return lines;
}

function isMihomoProxyGroup(group: ProxyGroup): boolean {
  return !['direct', 'reject'].includes(group.type);
}

// ─── Rule serialization ───────────────────────────────────────────────────────

function ruleToMihomo(rule: ProxyRule, groups: ProxyGroup[]): string {
  const group = groups.find((g) => g.id === rule.targetGroupId);
  const groupName = group ? resolveMihomoPolicyName(group) : rule.targetGroupId;

  if (rule.type === 'MATCH') {
    return `MATCH,${groupName}`;
  }

  const noResolve = rule.noResolve ? ',no-resolve' : '';
  return `${rule.type},${rule.payload},${groupName}${noResolve}`;
}

function defaultPolicyName(groups: ProxyGroup[]): string | undefined {
  const group = groups.find((item) => item.name === '漏网之鱼')
    ?? groups.find((item) => item.name === 'PROXY')
    ?? groups[0];
  return group ? resolveMihomoPolicyName(group) : undefined;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function escapeName(name: string): string {
  return name.replace(/"/g, '\\"');
}

function resolveMihomoPolicyName(group: ProxyGroup): string {
  if (group.type === 'direct') return 'DIRECT';
  if (group.type === 'reject') return 'REJECT';
  return escapeName(group.name);
}

function filterCollectionNodeNames(
  collectionNodeNames: Record<string, string[]>,
  allowedNames: Set<string>
): Record<string, string[]> {
  return Object.fromEntries(
    Object.entries(collectionNodeNames).map(([collectionId, names]) => [
      collectionId,
      names.filter((name) => allowedNames.has(name)),
    ])
  );
}
