import {
  DEFAULT_HEALTH_CHECK,
  DEFAULT_RULE_TARGET_GROUP_ID,
  isRuleSetFormatCompatible,
  resolveRuleForExport,
  getRuleNoResolveHandling,
} from '@uni-conf/shared';
import type { ExportDnsPolicy, ExportFormat, ProxyNode, ProxyGroup, ProxyRule, RemoteRuleSet } from '@uni-conf/types';
import { resolveRemoteRuleSetForExport } from './remote-rule-set-resolver';
import {
  DEFAULT_FAKE_IP_POLICY,
  MANAGED_FAKE_IP_FILTER_TAG,
  QUIXOTIC_FAKE_IP_FILTER_MRS_URL,
  customRealIpDomains,
  inlineRealIpDomains,
} from './dns-policy';

// ─── Mihomo YAML generator ────────────────────────────────────────────────────

interface MihomoGeneratorOptions {
  dnsPolicy?: ExportDnsPolicy;
  managedRealIpDomains?: string[];
  ruleSetConversionBaseUrl?: string;
  ruleSetExportFormat?: Extract<ExportFormat, 'mihomo' | 'clash' | 'stash'>;
}

export function generateMihomoYaml(
  nodes: ProxyNode[],
  groups: ProxyGroup[],
  rules: ProxyRule[],
  remoteSets: RemoteRuleSet[],
  collectionNodeNames: Record<string, string[]> = {},
  options: MihomoGeneratorOptions = {}
): string {
  const lines: string[] = [];
  const ruleSetExportFormat = options.ruleSetExportFormat ?? 'mihomo';
  const serializedNodes = nodes
    .map((node) => ({ node, proxy: nodeToMihomo(node, ruleSetExportFormat) }))
    .filter((item): item is { node: ProxyNode; proxy: string } => item.proxy !== null);
  const serializableNodes = serializedNodes.map((item) => item.node);
  const serializableNodeNames = new Set(serializableNodes.map((node) => node.name));
  const serializableCollectionNodeNames = filterCollectionNodeNames(collectionNodeNames, serializableNodeNames);

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push('# Generated by UniConf');
  lines.push(`# Generated at: ${new Date().toISOString()}`);
  lines.push('');

  // ── Basic settings ──────────────────────────────────────────────────────────
  lines.push('mixed-port: 7890');
  lines.push('allow-lan: false');
  lines.push('bind-address: "*"');
  lines.push('mode: rule');
  lines.push('log-level: warning');
  lines.push('ipv6: false');
  lines.push('external-controller: 127.0.0.1:9090');
  lines.push('');

  if (ruleSetExportFormat === 'mihomo') {
    lines.push('geodata-mode: true');
    lines.push('geodata-loader: memconservative');
    lines.push('geo-auto-update: true');
    lines.push('geo-update-interval: 24');
    lines.push('geox-url:');
    lines.push('  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"');
    lines.push('  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"');
    lines.push('  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"');
    lines.push('  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"');
    lines.push('');
  }

  const dnsPolicy = options.dnsPolicy ?? DEFAULT_FAKE_IP_POLICY;
  const useManagedFakeIpFilterProvider = options.ruleSetExportFormat !== 'stash';
  lines.push(
    ...(options.ruleSetExportFormat === 'stash'
      ? buildStashDnsLines(dnsPolicy, options.managedRealIpDomains)
      : buildMihomoDnsLines(dnsPolicy, useManagedFakeIpFilterProvider))
  );
  lines.push('');

  // ── Proxies ─────────────────────────────────────────────────────────────────
  if (serializedNodes.length === 0) {
    lines.push('proxies: []');
  } else {
    lines.push('proxies:');
    for (const { proxy } of serializedNodes) {
      lines.push(`  - ${proxy}`);
    }
  }
  lines.push('');

  // ── Proxy groups ─────────────────────────────────────────────────────────────
  const mihomoProxyGroups = groups.filter(isMihomoProxyGroup);
  if (mihomoProxyGroups.length === 0) {
    lines.push('proxy-groups: []');
  } else {
    lines.push('proxy-groups:');
    for (const group of mihomoProxyGroups) {
      lines.push(...groupToMihomo(group, serializableNodes, groups, serializableCollectionNodeNames));
    }
  }
  lines.push('');

  // ── Rule providers ────────────────────────────────────────────────────────────
  const enabledRemoteSets = sortRemoteRuleSets(remoteSets)
    .filter((rs) => rs.enabled)
    .map((rs) => ({
      source: rs,
      resolved: resolveRemoteRuleSetForExport(rs, ruleSetExportFormat, options.ruleSetConversionBaseUrl),
    }))
    .filter(
      (
        item
      ): item is {
        source: RemoteRuleSet;
        resolved: { url: string; format: RemoteRuleSet['format'] };
      } => Boolean(item.resolved) && isRuleSetFormatCompatible(ruleSetExportFormat, item.resolved!.format)
    );
  if (enabledRemoteSets.length === 0 && !useManagedFakeIpFilterProvider) {
    lines.push('rule-providers: {}');
  } else {
    lines.push('rule-providers:');
    if (useManagedFakeIpFilterProvider) {
      lines.push(`  ${MANAGED_FAKE_IP_FILTER_TAG}:`);
      lines.push('    type: http');
      lines.push('    behavior: domain');
      lines.push('    format: mrs');
      lines.push(`    url: "${QUIXOTIC_FAKE_IP_FILTER_MRS_URL}"`);
      lines.push(`    path: ./ruleset/${MANAGED_FAKE_IP_FILTER_TAG}.mrs`);
      lines.push('    interval: 86400');
    }
    for (const { source: rs, resolved } of enabledRemoteSets) {
      const safeName = rs.name.replace(/[^a-zA-Z0-9_-]/g, '_');
      lines.push(`  ${safeName}:`);
      lines.push(`    type: http`);
      lines.push(`    behavior: ${rs.behavior}`);
      if (resolved.format === 'mrs') lines.push(`    format: mrs`);
      lines.push(`    url: "${resolved.url}"`);
      lines.push(`    path: ./ruleset/${safeName}.${resolved.format === 'mrs' ? 'mrs' : 'yaml'}`);
      lines.push(`    interval: ${rs.updateInterval * 3600}`);
    }
  }
  lines.push('');

  // ── Rules ────────────────────────────────────────────────────────────────────
  const enabledRules = rules.filter((r) => r.enabled).sort((a, b) => a.order - b.order);
  const matchRule = enabledRules.find((r) => r.type === 'MATCH');

  lines.push('rules:');
  for (const rule of enabledRules) {
    if (rule.type === 'MATCH') continue;
    const line = ruleToMihomo(rule, groups);
    if (line) lines.push(`  - ${line}`);
  }

  for (const { source: rs } of enabledRemoteSets) {
    const safeName = rs.name.replace(/[^a-zA-Z0-9_-]/g, '_');
    const group = groups.find((g) => g.id === rs.targetGroupId);
    const targetGroup = group ? resolveMihomoPolicyName(group) : rs.targetGroupId;
    lines.push(`  - RULE-SET,${safeName},${targetGroup}`);
  }

  if (matchRule) {
    lines.push(`  - ${ruleToMihomo(matchRule, groups)!}`);
  } else {
    const defaultTarget = defaultPolicyName(groups);
    if (defaultTarget) {
      lines.push(`  - MATCH,${defaultTarget}`);
    } else {
      lines.push('  - MATCH,DIRECT');
    }
  }

  return lines.join('\n');
}

function buildMihomoDnsLines(policy: ExportDnsPolicy, useManagedFakeIpFilterProvider: boolean): string[] {
  const lines = ['dns:', '  enable: true', '  enhanced-mode: fake-ip'];

  lines.push('  fake-ip-range: 198.18.0.1/16');
  lines.push('  fake-ip-filter:');
  if (useManagedFakeIpFilterProvider) {
    lines.push(`    - "rule-set:${MANAGED_FAKE_IP_FILTER_TAG}"`);
  }
  for (const domain of customRealIpDomains(policy)) lines.push(`    - "${domain}"`);

  lines.push('  default-nameserver:');
  lines.push('    - 223.5.5.5');
  lines.push('    - 119.29.29.29');
  lines.push('  nameserver:');
  lines.push('    - https://223.5.5.5/dns-query');
  lines.push('    - https://120.53.53.53/dns-query');

  if (policy.resolutionMode === 'single') {
    return lines;
  }

  lines.push('  fallback:');
  lines.push('    - tls://8.8.8.8');
  lines.push('    - tls://1.1.1.1');
  lines.push('  fallback-filter:');
  lines.push('    geoip: true');
  lines.push('    geoip-code: CN');
  lines.push('    ipcidr:');
  lines.push('      - 240.0.0.0/4');
  lines.push('  nameserver-policy:');
  lines.push('    "geosite:cn":');
  lines.push('      - https://223.5.5.5/dns-query');
  lines.push('      - https://120.53.53.53/dns-query');
  return lines;
}

function buildStashDnsLines(policy: ExportDnsPolicy, managedDomains?: string[]): string[] {
  const lines = [
    'dns:',
    '  enable: true',
    '  default-nameserver:',
    '    - 223.5.5.5',
    '    - 119.29.29.29',
    '  nameserver:',
    '    - https://223.5.5.5/dns-query',
    '    - https://120.53.53.53/dns-query',
  ];
  lines.push('  fake-ip-filter:');
  for (const domain of inlineRealIpDomains(policy, 'stash', managedDomains)) lines.push(`    - "${domain}"`);
  if (policy.resolutionMode === 'split') {
    lines.push('  nameserver-policy:');
    lines.push('    "geosite:cn":');
    lines.push('      - https://223.5.5.5/dns-query');
    lines.push('      - https://120.53.53.53/dns-query');
    lines.push('    "geosite:geolocation-!cn":');
    lines.push('      - https://1.1.1.1/dns-query');
    lines.push('      - https://8.8.8.8/dns-query');
  }
  return lines;
}

function sortRemoteRuleSets(remoteSets: RemoteRuleSet[]): RemoteRuleSet[] {
  return [...remoteSets].sort((a, b) => a.sortOrder - b.sortOrder || a.createdAt.localeCompare(b.createdAt));
}

// ─── Node serialization ───────────────────────────────────────────────────────

function nodeToMihomo(
  node: ProxyNode,
  target: Extract<ExportFormat, 'mihomo' | 'clash' | 'stash'>
): string | null {
  const nativeProxy = nativeMihomoProxy(node);
  if (nativeProxy) return JSON.stringify(nativeProxy);

  const cfg = node.parsedConfig;
  const name = escapeName(node.name);

  switch (node.protocol) {
    case 'ss': {
      const method = (cfg.extra?.cipher as string) ?? (cfg.extra?.method as string) ?? 'aes-256-gcm';
      const pass = cfg.password ?? '';
      return `{name: "${name}", type: ss, server: ${node.server}, port: ${node.port}, cipher: "${method}", password: "${pass}"}`;
    }
    case 'ssr': {
      const method = (cfg.extra?.cipher as string) ?? (cfg.extra?.method as string) ?? 'aes-256-cfb';
      const pass = cfg.password ?? '';
      const protocol = (cfg.extra?.protocol as string) ?? 'origin';
      const obfs = (cfg.extra?.obfs as string) ?? 'plain';
      let obj = `{name: "${name}", type: ssr, server: ${node.server}, port: ${node.port}, cipher: "${method}", password: "${pass}", protocol: "${protocol}", obfs: "${obfs}"`;
      if (cfg.extra?.protocolParam) obj += `, protocol-param: "${String(cfg.extra.protocolParam)}"`;
      if (cfg.extra?.obfsParam) obj += `, obfs-param: "${String(cfg.extra.obfsParam)}"`;
      obj += '}';
      return obj;
    }
    case 'vmess': {
      const uuid = cfg.uuid ?? '';
      const alterId = (cfg.extra?.alterId as number) ?? 0;
      const network = cfg.network ?? 'tcp';
      const cipher = (cfg.extra?.cipher as string | undefined) ?? (cfg.extra?.security as string | undefined) ?? 'auto';
      let obj = `{name: "${name}", type: vmess, server: ${node.server}, port: ${node.port}, uuid: "${uuid}", alterId: ${alterId}, cipher: ${cipher}, tls: ${cfg.tls ?? false}, network: "${network}"`;
      if (network === 'ws') {
        const wsPath = cfg.wsPath ?? '/';
        obj += `, ws-opts: {path: "${wsPath}"`;
        if (cfg.wsHeaders && Object.keys(cfg.wsHeaders).length > 0) {
          const host = cfg.wsHeaders['Host'] ?? cfg.wsHeaders['host'] ?? node.server;
          obj += `, headers: {Host: "${host}"}`;
        }
        obj += '}';
      }
      if (cfg.sni) obj += `, servername: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'vless': {
      const uuid = cfg.uuid ?? '';
      const network = cfg.network ?? 'tcp';
      const flow = (cfg.extra?.flow as string) ?? '';
      let obj = `{name: "${name}", type: vless, server: ${node.server}, port: ${node.port}, uuid: "${uuid}", tls: ${cfg.tls ?? false}, network: "${network}"`;
      if (flow) obj += `, flow: "${flow}"`;
      if (cfg.sni) obj += `, servername: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      const reality = vlessRealityOptions(cfg.extra);
      if (reality) {
        obj += `, reality-opts: {public-key: "${reality.publicKey}", short-id: "${reality.shortId}"}`;
      }
      obj += '}';
      return obj;
    }
    case 'trojan': {
      const pass = cfg.password ?? '';
      let obj = `{name: "${name}", type: trojan, server: ${node.server}, port: ${node.port}, password: "${pass}"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'hysteria2': {
      const pass = cfg.password ?? (cfg.extra?.auth as string) ?? '';
      const obfs = cfg.extra?.obfs as string | undefined;
      const obfsPassword = cfg.extra?.obfsPassword as string | undefined;
      const credentialField = target === 'stash' ? 'auth' : 'password';
      let obj = `{name: "${name}", type: hysteria2, server: ${node.server}, port: ${node.port}, ${credentialField}: "${pass}"`;
      if (obfs) obj += `, obfs: "${obfs}"`;
      if (obfsPassword) obj += `, obfs-password: "${obfsPassword}"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'hysteria': {
      const authStr = cfg.password ?? (cfg.extra?.authStr as string) ?? (cfg.extra?.auth as string) ?? '';
      const protocol = (cfg.extra?.protocol as string) ?? 'udp';
      const upMbps = (cfg.extra?.upMbps as number) ?? 100;
      const downMbps = (cfg.extra?.downMbps as number) ?? 100;
      const bandwidthFields = target === 'stash'
        ? `up-speed: ${upMbps}, down-speed: ${downMbps}`
        : `up: "${upMbps} Mbps", down: "${downMbps} Mbps"`;
      let obj = `{name: "${name}", type: hysteria, server: ${node.server}, port: ${node.port}, auth-str: "${authStr}", protocol: "${protocol}", ${bandwidthFields}`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'tuic': {
      const uuid = cfg.uuid ?? '';
      const pass = cfg.password ?? '';
      let obj = `{name: "${name}", type: tuic, server: ${node.server}, port: ${node.port}`;
      if (target === 'stash') obj += ', version: 5';
      obj += `, uuid: "${uuid}", password: "${pass}"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'wireguard': {
      const addresses = configStringArray(cfg.extra?.ip ?? cfg.extra?.localAddress);
      const ipv4 = addresses.find((address) => !address.includes(':'))?.split('/', 1)[0];
      const ipv6 = addresses.find((address) => address.includes(':'))?.split('/', 1)[0];
      const allowedIps = configStringArray(
        cfg.extra?.allowedIPs ?? cfg.extra?.allowedIps ?? cfg.extra?.allowed_ips
      );
      const dns = configStringArray(cfg.extra?.dns);
      const reserved = normalizeWireGuardReserved(cfg.extra?.reserved);
      const keepalive = cfg.extra?.keepalive ?? cfg.extra?.persistentKeepalive;
      const privateKey = String(cfg.extra?.privateKey ?? cfg.extra?.['private-key'] ?? '');
      const publicKey = String(cfg.extra?.publicKey ?? cfg.extra?.['public-key'] ?? '');
      if (!privateKey || !publicKey || (!ipv4 && !ipv6)) return null;
      return JSON.stringify({
        name: node.name,
        type: 'wireguard',
        server: node.server,
        port: node.port,
        ip: ipv4,
        ...(ipv6 ? { ipv6 } : {}),
        'private-key': privateKey,
        'public-key': publicKey,
        ...(cfg.extra?.presharedKey || cfg.extra?.['pre-shared-key']
          ? { 'pre-shared-key': String(cfg.extra?.presharedKey ?? cfg.extra?.['pre-shared-key']) }
          : {}),
        'allowed-ips': allowedIps.length > 0 ? allowedIps : ['0.0.0.0/0'],
        ...(reserved ? { reserved } : {}),
        ...(keepalive !== undefined
          ? { [target === 'stash' ? 'keepalive' : 'persistent-keepalive']: Number(keepalive) }
          : {}),
        ...(cfg.extra?.mtu !== undefined ? { mtu: Number(cfg.extra.mtu) } : {}),
        ...(dns.length > 0 ? { dns } : {}),
        udp: cfg.extra?.udp === undefined ? true : Boolean(cfg.extra.udp),
      });
    }
    case 'ssh': {
      const username = String(cfg.extra?.username ?? cfg.extra?.user ?? '');
      const hostKeys = configStringArray(cfg.extra?.hostKeys ?? cfg.extra?.['host-key']);
      const privateKey = cfg.extra?.privateKey ?? cfg.extra?.['private-key'];
      if (!username || (!cfg.password && !privateKey)) return null;
      return JSON.stringify({
        name: node.name,
        type: 'ssh',
        server: node.server,
        port: node.port,
        [target === 'stash' ? 'user' : 'username']: username,
        ...(cfg.password ? { password: cfg.password } : {}),
        ...(privateKey
          ? { 'private-key': String(privateKey) }
          : {}),
        ...(cfg.extra?.privateKeyPassphrase || cfg.extra?.['private-key-passphrase']
          ? {
              'private-key-passphrase': String(
                cfg.extra?.privateKeyPassphrase ?? cfg.extra?.['private-key-passphrase']
              ),
            }
          : {}),
        ...(target !== 'stash' && hostKeys.length > 0 ? { 'host-key': hostKeys } : {}),
      });
    }
    case 'snell': {
      const psk = String(cfg.extra?.psk ?? cfg.password ?? '');
      if (!psk) return null;
      const obfs = String(cfg.extra?.obfs ?? '');
      return JSON.stringify({
        name: node.name,
        type: 'snell',
        server: node.server,
        port: node.port,
        psk,
        version: Number(cfg.extra?.version ?? 4),
        udp: cfg.extra?.udp === undefined ? true : Boolean(cfg.extra.udp),
        ...(cfg.extra?.reuse !== undefined ? { reuse: Boolean(cfg.extra.reuse) } : {}),
        ...(['http', 'tls'].includes(obfs)
          ? {
              'obfs-opts': {
                mode: obfs,
                ...(cfg.extra?.obfsHost ? { host: String(cfg.extra.obfsHost) } : {}),
              },
            }
          : {}),
      });
    }
    case 'mieru': {
      if (target === 'stash') return null;
      const username = String(cfg.extra?.username ?? '');
      const password = String(cfg.password ?? cfg.extra?.password ?? '');
      if (!username || !password) return null;
      return JSON.stringify({
        name: node.name,
        type: 'mieru',
        server: node.server,
        port: node.port,
        username,
        password,
        transport: String(cfg.extra?.transport ?? 'TCP').toUpperCase(),
        multiplexing: String(cfg.extra?.multiplexing ?? 'MULTIPLEXING_LOW'),
        ...(cfg.extra?.trafficPattern
          ? { 'traffic-pattern': String(cfg.extra.trafficPattern) }
          : {}),
      });
    }
    case 'sudoku': {
      if (target === 'stash') return null;
      const key = String(cfg.extra?.key ?? cfg.password ?? '');
      if (!key) return null;
      return JSON.stringify({
        name: node.name,
        type: 'sudoku',
        server: node.server,
        port: node.port,
        key,
        'aead-method': String(cfg.extra?.aeadMethod ?? 'chacha20-poly1305'),
        'padding-min': Number(cfg.extra?.paddingMin ?? 2),
        'padding-max': Number(cfg.extra?.paddingMax ?? 7),
        'table-type': String(cfg.extra?.tableType ?? 'prefer_ascii'),
        httpmask: {
          disable: Boolean(cfg.extra?.httpMaskDisable ?? false),
          mode: String(cfg.extra?.httpMaskMode ?? 'legacy'),
          tls: Boolean(cfg.extra?.httpMaskTls ?? false),
          'mask-host': String(cfg.extra?.httpMaskHost ?? ''),
          'path-root': String(cfg.extra?.httpMaskPathRoot ?? ''),
          multiplex: String(cfg.extra?.httpMaskMultiplex ?? 'off'),
        },
        'enable-pure-downlink': Boolean(cfg.extra?.enablePureDownlink ?? false),
      });
    }
    case 'trusttunnel': {
      const username = String(cfg.extra?.username ?? '');
      const password = String(cfg.password ?? cfg.extra?.password ?? '');
      if (!username || !password) return null;
      const alpn = configStringArray(cfg.extra?.alpn);
      return JSON.stringify({
        name: node.name,
        type: 'trusttunnel',
        server: node.server,
        port: node.port,
        username,
        password,
        ...(cfg.sni ? { sni: cfg.sni } : {}),
        ...(alpn.length > 0 ? { alpn } : {}),
        ...(cfg.skipCertVerify !== undefined ? { 'skip-cert-verify': Boolean(cfg.skipCertVerify) } : {}),
        ...(cfg.extra?.quic !== undefined ? { quic: Boolean(cfg.extra.quic) } : {}),
        udp: cfg.extra?.udp === undefined ? true : Boolean(cfg.extra.udp),
      });
    }
    case 'juicity': {
      if (target !== 'stash') return null;
      const uuid = String(cfg.uuid ?? '');
      const password = String(cfg.password ?? '');
      if (!uuid || !password) return null;
      const alpn = configStringArray(cfg.extra?.alpn);
      return JSON.stringify({
        name: node.name,
        type: 'juicity',
        server: node.server,
        port: node.port,
        uuid,
        password,
        ...(cfg.sni ? { sni: cfg.sni } : {}),
        alpn: alpn.length > 0 ? alpn : ['h3'],
        ...(cfg.skipCertVerify !== undefined ? { 'skip-cert-verify': Boolean(cfg.skipCertVerify) } : {}),
      });
    }
    case 'masque': {
      if (target === 'stash') return null;
      const privateKey = String(cfg.extra?.privateKey ?? cfg.extra?.['private-key'] ?? '');
      const publicKey = String(cfg.extra?.publicKey ?? cfg.extra?.['public-key'] ?? '');
      if (!privateKey || !publicKey) return null;
      const dns = configStringArray(cfg.extra?.dns);
      return JSON.stringify({
        name: node.name,
        type: 'masque',
        server: node.server,
        port: node.port,
        'private-key': privateKey,
        'public-key': publicKey,
        ...(cfg.extra?.ip ? { ip: String(cfg.extra.ip) } : {}),
        ...(cfg.extra?.ipv6 ? { ipv6: String(cfg.extra.ipv6) } : {}),
        ...(cfg.extra?.mtu !== undefined ? { mtu: Number(cfg.extra.mtu) } : {}),
        ...(cfg.extra?.udp !== undefined ? { udp: Boolean(cfg.extra.udp) } : {}),
        ...(cfg.sni ? { sni: cfg.sni } : {}),
        ...(cfg.extra?.network ? { network: String(cfg.extra.network) } : {}),
        ...(cfg.extra?.remoteDnsResolve !== undefined || cfg.extra?.['remote-dns-resolve'] !== undefined
          ? {
              'remote-dns-resolve': Boolean(
                cfg.extra?.remoteDnsResolve ?? cfg.extra?.['remote-dns-resolve']
              ),
            }
          : {}),
        ...(dns.length > 0 ? { dns } : {}),
        ...(cfg.extra?.congestionController || cfg.extra?.['congestion-controller']
          ? {
              'congestion-controller': String(
                cfg.extra?.congestionController ?? cfg.extra?.['congestion-controller']
              ),
            }
          : {}),
        ...(cfg.extra?.handshakeTimeout !== undefined || cfg.extra?.['handshake-timeout'] !== undefined
          ? {
              'handshake-timeout': Number(
                cfg.extra?.handshakeTimeout ?? cfg.extra?.['handshake-timeout']
              ),
            }
          : {}),
      });
    }
    case 'anytls': {
      const pass = cfg.password ?? '';
      const fingerprint = anytlsFingerprint(cfg.extra);
      const alpn = cfg.extra?.alpn;
      let obj = `{name: "${name}", type: anytls, server: ${node.server}, port: ${node.port}, password: "${pass}"`;
      if (fingerprint) obj += `, client-fingerprint: "${fingerprint}"`;
      if (cfg.extra?.udp !== undefined) obj += `, udp: ${Boolean(cfg.extra.udp)}`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (Array.isArray(alpn) && alpn.length > 0) {
        obj += `, alpn: [${alpn.map((item) => `"${String(item)}"`).join(', ')}]`;
      }
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'socks5': {
      let obj = `{name: "${name}", type: socks5, server: ${node.server}, port: ${node.port}`;
      if (cfg.extra?.username) obj += `, username: "${cfg.extra.username}"`;
      if (cfg.password) obj += `, password: "${cfg.password}"`;
      if (cfg.tls) obj += `, tls: true`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'http':
    case 'https': {
      let obj = `{name: "${name}", type: http, server: ${node.server}, port: ${node.port}`;
      if (cfg.extra?.username) obj += `, username: "${cfg.extra.username}"`;
      if (cfg.password) obj += `, password: "${cfg.password}"`;
      if (node.protocol === 'https' || cfg.tls) obj += `, tls: true`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    default:
      return null;
  }
}

function nativeMihomoProxy(node: ProxyNode): Record<string, unknown> | null {
  const raw = nativeObject(node.rawConfig, 'mihomo');
  if (!isMihomoProxyShape(raw)) return null;
  return {
    ...raw,
    name: node.name,
    server: node.server,
    port: node.port,
  };
}

function vlessRealityOptions(
  extra: Record<string, unknown> | undefined
): { publicKey: string; shortId: string } | null {
  if (!extra) return null;
  const nested =
    extra.reality && typeof extra.reality === 'object' && !Array.isArray(extra.reality)
      ? (extra.reality as Record<string, unknown>)
      : {};
  const publicKey = configString(extra.publicKey) ?? configString(nested.publicKey);
  const shortId = configString(extra.shortId) ?? configString(nested.shortId) ?? '';
  return publicKey ? { publicKey, shortId } : null;
}

function configString(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function anytlsFingerprint(extra: Record<string, unknown> | undefined): string | undefined {
  return (
    configString(extra?.['client-fingerprint']) ??
    configString(extra?.clientFingerprint) ??
    configString(extra?.fingerprint) ??
    configString(extra?.fp)
  );
}

function nativeObject(rawConfig: unknown, key: string): Record<string, unknown> | null {
  if (!rawConfig || typeof rawConfig !== 'object' || Array.isArray(rawConfig)) return null;
  const raw = rawConfig as Record<string, unknown>;
  const nested = raw[key];
  if (nested && typeof nested === 'object' && !Array.isArray(nested)) return nested as Record<string, unknown>;
  return raw;
}

function isMihomoProxyShape(value: Record<string, unknown> | null): value is Record<string, unknown> {
  return Boolean(value && typeof value.type === 'string' && value.port !== undefined && value.server !== undefined);
}

// ─── Group serialization ──────────────────────────────────────────────────────

function groupToMihomo(
  group: ProxyGroup,
  allNodes: ProxyNode[],
  allGroups: ProxyGroup[],
  collectionNodeNames: Record<string, string[]>
): string[] {
  const lines: string[] = [];
  const name = escapeName(group.name);

  lines.push(`  - name: "${name}"`);
  lines.push(`    type: ${group.type}`);

  const proxies: string[] = [];

  for (const b of group.builtins) {
    proxies.push(b);
  }

  for (const gid of group.groupIds) {
    const nestedGroup = allGroups.find((item) => item.id === gid);
    if (nestedGroup) proxies.push(resolveMihomoPolicyName(nestedGroup));
  }

  const collectionNames = group.collectionIds.flatMap((id) => collectionNodeNames[id] ?? []);
  if (collectionNames.length > 0) {
    for (const nodeName of collectionNames) proxies.push(escapeName(nodeName));
  } else if (group.collectionIds.length === 0 && group.groupIds.length === 0 && group.builtins.length === 0) {
    for (const node of allNodes) proxies.push(escapeName(node.name));
  }

  const dedupedProxies = [...new Set(proxies)];
  if (dedupedProxies.length === 0) dedupedProxies.push('DIRECT');

  lines.push(`    proxies:`);
  for (const p of dedupedProxies) {
    lines.push(`      - "${p}"`);
  }

  if (['url-test', 'fallback', 'load-balance'].includes(group.type)) {
    lines.push(`    url: "${group.testUrl ?? DEFAULT_HEALTH_CHECK.testUrl}"`);
    lines.push(`    interval: ${group.interval ?? DEFAULT_HEALTH_CHECK.interval}`);
    if (group.tolerance !== undefined) {
      lines.push(`    tolerance: ${group.tolerance}`);
    }
    if (group.lazy !== undefined) {
      lines.push(`    lazy: ${group.lazy}`);
    }
  }

  return lines;
}

function isMihomoProxyGroup(group: ProxyGroup): boolean {
  return !['direct', 'reject'].includes(group.type);
}

// ─── Rule serialization ───────────────────────────────────────────────────────

function ruleToMihomo(rule: ProxyRule, groups: ProxyGroup[]): string | null {
  const group = groups.find((g) => g.id === rule.targetGroupId);
  const groupName = group ? resolveMihomoPolicyName(group) : rule.targetGroupId;

  if (rule.type === 'MATCH') {
    return `MATCH,${groupName}`;
  }

  const resolution = resolveRuleForExport(rule.type, rule.payload, 'mihomo');
  if (resolution.level === 'unsupported') return null;
  const noResolve = rule.noResolve && getRuleNoResolveHandling(rule.type, 'mihomo') === 'native' ? ',no-resolve' : '';
  return `${resolution.type},${resolution.payload},${groupName}${noResolve}`;
}

function defaultPolicyName(groups: ProxyGroup[]): string | undefined {
  const group = groups.find((item) => item.id === DEFAULT_RULE_TARGET_GROUP_ID);
  return group ? resolveMihomoPolicyName(group) : undefined;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function escapeName(name: string): string {
  return name.replace(/"/g, '\\"');
}

function configStringArray(value: unknown): string[] {
  if (Array.isArray(value)) return value.map(String).map((item) => item.trim()).filter(Boolean);
  if (typeof value !== 'string') return [];
  return value.split(',').map((item) => item.trim()).filter(Boolean);
}

function normalizeWireGuardReserved(value: unknown): number[] | string | undefined {
  if (Array.isArray(value)) {
    const bytes = value.map(Number);
    return bytes.length === 3 && bytes.every((byte) => Number.isInteger(byte) && byte >= 0 && byte <= 255)
      ? bytes
      : undefined;
  }
  if (typeof value !== 'string' || !value) return undefined;
  const bytes = value.split(',').map((item) => Number(item.trim()));
  return bytes.length === 3 && bytes.every((byte) => Number.isInteger(byte) && byte >= 0 && byte <= 255)
    ? bytes
    : value;
}

function resolveMihomoPolicyName(group: ProxyGroup): string {
  if (group.type === 'direct') return 'DIRECT';
  if (group.type === 'reject') return 'REJECT';
  return escapeName(group.name);
}

function filterCollectionNodeNames(
  collectionNodeNames: Record<string, string[]>,
  allowedNames: Set<string>
): Record<string, string[]> {
  return Object.fromEntries(
    Object.entries(collectionNodeNames).map(([collectionId, names]) => [
      collectionId,
      names.filter((name) => allowedNames.has(name)),
    ])
  );
}
