import type { ProxyNode, ProxyGroup, ProxyRule, RemoteRuleSet } from '@uni-conf/types';

// ─── Mihomo YAML generator ────────────────────────────────────────────────────

export function generateMihomoYaml(
  nodes: ProxyNode[],
  groups: ProxyGroup[],
  rules: ProxyRule[],
  remoteSets: RemoteRuleSet[]
): string {
  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push('# Generated by UniConf');
  lines.push(`# Generated at: ${new Date().toISOString()}`);
  lines.push('');

  // ── Basic settings ──────────────────────────────────────────────────────────
  lines.push('port: 7890');
  lines.push('socks-port: 7891');
  lines.push('redir-port: 7892');
  lines.push('allow-lan: false');
  lines.push('bind-address: "*"');
  lines.push('mode: rule');
  lines.push('log-level: info');
  lines.push('ipv6: false');
  lines.push('external-controller: 127.0.0.1:9090');
  lines.push('');

  // ── DNS ─────────────────────────────────────────────────────────────────────
  lines.push('dns:');
  lines.push('  enable: true');
  lines.push('  enhanced-mode: fake-ip');
  lines.push('  fake-ip-range: 198.18.0.1/16');
  lines.push('  fake-ip-filter:');
  lines.push('    - "*.lan"');
  lines.push('    - "*.local"');
  lines.push('    - "localhost.ptlogin2.qq.com"');
  lines.push('  nameserver:');
  lines.push('    - 8.8.8.8');
  lines.push('    - 1.1.1.1');
  lines.push('    - 223.5.5.5');
  lines.push('  fallback:');
  lines.push('    - 8.8.4.4');
  lines.push('    - 1.0.0.1');
  lines.push('  fallback-filter:');
  lines.push('    geoip: true');
  lines.push('    geoip-code: CN');
  lines.push('    ipcidr:');
  lines.push('      - 240.0.0.0/4');
  lines.push('');

  // ── Proxies ─────────────────────────────────────────────────────────────────
  if (nodes.length === 0) {
    lines.push('proxies: []');
  } else {
    lines.push('proxies:');
    for (const node of nodes) {
      const proxy = nodeToMihomo(node);
      if (proxy) {
        lines.push(`  - ${proxy}`);
      }
    }
  }
  lines.push('');

  // ── Proxy groups ─────────────────────────────────────────────────────────────
  if (groups.length === 0) {
    lines.push('proxy-groups: []');
  } else {
    lines.push('proxy-groups:');
    for (const group of groups) {
      lines.push(...groupToMihomo(group, nodes));
    }
  }
  lines.push('');

  // ── Rule providers ────────────────────────────────────────────────────────────
  const enabledRemoteSets = remoteSets.filter((rs) => rs.enabled);
  if (enabledRemoteSets.length === 0) {
    lines.push('rule-providers: {}');
  } else {
    lines.push('rule-providers:');
    for (const rs of enabledRemoteSets) {
      const safeName = rs.name.replace(/[^a-zA-Z0-9_-]/g, '_');
      lines.push(`  ${safeName}:`);
      lines.push(`    type: http`);
      lines.push(`    behavior: ${detectBehavior(rs.format)}`);
      lines.push(`    url: "${rs.url}"`);
      lines.push(`    path: ./ruleset/${safeName}.yaml`);
      lines.push(`    interval: ${rs.updateInterval * 3600}`);
    }
  }
  lines.push('');

  // ── Rules ────────────────────────────────────────────────────────────────────
  const enabledRules = rules
    .filter((r) => r.enabled)
    .sort((a, b) => a.order - b.order);

  lines.push('rules:');
  for (const rule of enabledRules) {
    lines.push(`  - ${ruleToMihomo(rule, groups)}`);
  }
  // Fallback MATCH rule
  const hasMatch = enabledRules.some((r) => r.type === 'MATCH');
  if (!hasMatch) {
    const proxyGroup = groups.find((g) => g.name === 'PROXY') ?? groups[0];
    if (proxyGroup) {
      lines.push(`  - MATCH,${proxyGroup.name}`);
    } else {
      lines.push('  - MATCH,DIRECT');
    }
  }

  return lines.join('\n');
}

// ─── Node serialization ───────────────────────────────────────────────────────

function nodeToMihomo(node: ProxyNode): string | null {
  const cfg = node.parsedConfig;
  const name = escapeName(node.name);

  switch (node.protocol) {
    case 'ss': {
      const method = (cfg.extra?.cipher as string) ?? (cfg.extra?.method as string) ?? 'aes-256-gcm';
      const pass = cfg.password ?? '';
      return `{name: "${name}", type: ss, server: ${node.server}, port: ${node.port}, cipher: "${method}", password: "${pass}"}`;
    }
    case 'vmess': {
      const uuid = cfg.uuid ?? '';
      const alterId = (cfg.extra?.alterId as number) ?? 0;
      const network = cfg.network ?? 'tcp';
      let obj = `{name: "${name}", type: vmess, server: ${node.server}, port: ${node.port}, uuid: "${uuid}", alterId: ${alterId}, cipher: auto, tls: ${cfg.tls ?? false}, network: "${network}"`;
      if (network === 'ws') {
        const wsPath = cfg.wsPath ?? '/';
        obj += `, ws-opts: {path: "${wsPath}"`;
        if (cfg.wsHeaders && Object.keys(cfg.wsHeaders).length > 0) {
          const host = cfg.wsHeaders['Host'] ?? cfg.wsHeaders['host'] ?? node.server;
          obj += `, headers: {Host: "${host}"}`;
        }
        obj += '}';
      }
      if (cfg.sni) obj += `, servername: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'vless': {
      const uuid = cfg.uuid ?? '';
      const network = cfg.network ?? 'tcp';
      const flow = (cfg.extra?.flow as string) ?? '';
      let obj = `{name: "${name}", type: vless, server: ${node.server}, port: ${node.port}, uuid: "${uuid}", tls: ${cfg.tls ?? false}, network: "${network}"`;
      if (flow) obj += `, flow: "${flow}"`;
      if (cfg.sni) obj += `, servername: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      const reality = cfg.extra?.reality as Record<string, unknown> | undefined;
      if (reality) {
        obj += `, reality-opts: {public-key: "${reality.publicKey ?? ''}", short-id: "${reality.shortId ?? ''}"}`;
      }
      obj += '}';
      return obj;
    }
    case 'trojan': {
      const pass = cfg.password ?? '';
      let obj = `{name: "${name}", type: trojan, server: ${node.server}, port: ${node.port}, password: "${pass}"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'hysteria2': {
      const pass = cfg.password ?? (cfg.extra?.auth as string) ?? '';
      let obj = `{name: "${name}", type: hysteria2, server: ${node.server}, port: ${node.port}, password: "${pass}"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'hysteria': {
      const authStr = (cfg.extra?.authStr as string) ?? (cfg.extra?.auth as string) ?? '';
      const protocol = (cfg.extra?.protocol as string) ?? 'udp';
      const upMbps = (cfg.extra?.upMbps as number) ?? 100;
      const downMbps = (cfg.extra?.downMbps as number) ?? 100;
      let obj = `{name: "${name}", type: hysteria, server: ${node.server}, port: ${node.port}, auth-str: "${authStr}", protocol: "${protocol}", up: "${upMbps} Mbps", down: "${downMbps} Mbps"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'tuic': {
      const uuid = cfg.uuid ?? '';
      const pass = cfg.password ?? '';
      let obj = `{name: "${name}", type: tuic, server: ${node.server}, port: ${node.port}, uuid: "${uuid}", password: "${pass}"`;
      if (cfg.sni) obj += `, sni: "${cfg.sni}"`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'socks5': {
      let obj = `{name: "${name}", type: socks5, server: ${node.server}, port: ${node.port}`;
      if (cfg.extra?.username) obj += `, username: "${cfg.extra.username}"`;
      if (cfg.password) obj += `, password: "${cfg.password}"`;
      if (cfg.tls) obj += `, tls: true`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    case 'http':
    case 'https': {
      let obj = `{name: "${name}", type: http, server: ${node.server}, port: ${node.port}`;
      if (cfg.extra?.username) obj += `, username: "${cfg.extra.username}"`;
      if (cfg.password) obj += `, password: "${cfg.password}"`;
      if (node.protocol === 'https' || cfg.tls) obj += `, tls: true`;
      if (cfg.skipCertVerify) obj += `, skip-cert-verify: true`;
      obj += '}';
      return obj;
    }
    default:
      return null;
  }
}

// ─── Group serialization ──────────────────────────────────────────────────────

function groupToMihomo(group: ProxyGroup, allNodes: ProxyNode[]): string[] {
  const lines: string[] = [];
  const name = escapeName(group.name);

  lines.push(`  - name: "${name}"`);
  lines.push(`    type: ${group.type}`);

  // Build proxies list: builtins + group references + node names from collection (simplified)
  const proxies: string[] = [];

  for (const b of group.builtins) {
    proxies.push(b);
  }

  for (const gid of group.groupIds) {
    // Reference by id; ideally we'd resolve to name — store name in groupIds not possible here
    // We'll use the id as placeholder; actual resolution happens at runtime via name lookup
    proxies.push(gid);
  }

  // Add nodes (simplified: all nodes if no collectionIds; real implementation would filter)
  if (group.collectionIds.length === 0 && group.groupIds.length === 0 && group.builtins.length === 0) {
    for (const node of allNodes.slice(0, 50)) {
      proxies.push(escapeName(node.name));
    }
  }

  if (proxies.length === 0) {
    proxies.push('DIRECT');
  }

  lines.push(`    proxies:`);
  for (const p of proxies) {
    lines.push(`      - "${p}"`);
  }

  if (['url-test', 'fallback', 'load-balance'].includes(group.type)) {
    lines.push(`    url: "${group.testUrl ?? 'http://www.gstatic.com/generate_204'}"`);
    lines.push(`    interval: ${group.interval ?? 300}`);
    if (group.tolerance !== undefined) {
      lines.push(`    tolerance: ${group.tolerance}`);
    }
    if (group.lazy !== undefined) {
      lines.push(`    lazy: ${group.lazy}`);
    }
  }

  return lines;
}

// ─── Rule serialization ───────────────────────────────────────────────────────

function ruleToMihomo(rule: ProxyRule, groups: ProxyGroup[]): string {
  const group = groups.find((g) => g.id === rule.targetGroupId);
  const groupName = group ? escapeName(group.name) : rule.targetGroupId;

  if (rule.type === 'MATCH') {
    return `MATCH,${groupName}`;
  }

  const noResolve = rule.noResolve ? ',no-resolve' : '';
  return `${rule.type},${rule.payload},${groupName}${noResolve}`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function escapeName(name: string): string {
  return name.replace(/"/g, '\\"');
}

function detectBehavior(format: string): string {
  if (format === 'text') return 'domain';
  return 'classical';
}
